### ISSUE TITLE
Improve PR template

### ISSUE THREAD

**Issue by ananya-agrawal** [opencodeiiita/CodeFemme#32]
1. Add a field to upload live link
2. Remove the gap between " # and (issue) in fixes
3. Add a field to upload screenshot of the issue solved 
4. Comment down the way to check the checklist boxes

**Comment by Archies11** [comment]
@opencodebot claim

**Comment by dhairyabaweja** [comment]
@opencodebot claim

**Comment by samagragupta** [comment]
@opencodebot claim

**Comment by samagragupta** [comment]
@opencodebot claim
