### ISSUE TITLE
Add proper content in about section instead of Lorem Ipsum

### ISSUE THREAD

**Issue by CleverFool77** [opencodeiiita/CodeFemme#50]
## Current Behaviour 
Right now about section is filled with lorem ipsum text

## Expected Behaviour
Replace with useful content

**Comment by Archies11** [comment]
@opencodebot claim

**Comment by Archies11** [comment]
@opencodebot claim

**Comment by CleverFool77** [comment]
@Archies11 This issue isn't approved yet, so let it approve then start working with it.
