### ISSUE TITLE
spacing between contributors cards is changed. fix it.

### ISSUE THREAD

**Issue by Archies11** [opencodeiiita/CodeFemme#68]
the space was larger previously, increase it again.

**Comment by Anupam-dagar** [comment]
can you attach any screenshot or anything for the issue because the spacing looks fine to me.

**Comment by Archies11** [comment]
![capture](https://user-images.githubusercontent.com/45824817/52200277-5c44f180-288e-11e9-87ba-b599d99578b9.PNG)

**Comment by Anupam-dagar** [comment]
i suppose this is the current spacing. I meant the visual difference which I can see for the spacing. previous and current
