### ISSUE TITLE
Replace codefemme logo text with logo on website landing page.

### ISSUE THREAD

**Issue by Anupam-dagar** [opencodeiiita/CodeFemme#80]
Use the logo in this comment 
https://github.com/opencodeiiita/CodeFemme/issues/7#issuecomment-460278244

**Comment by Archies11** [comment]
@opencodebot claim

**Comment by Archies11** [comment]
@Anupam-dagar There are two options fir the logo in the aforementioned comment. I think the one without the white background will look better. Will that be OK?
