### ISSUE TITLE
Add testimonial of last time girls repo winner.

### ISSUE THREAD

**Issue by Anupam-dagar** [opencodeiiita/CodeFemme#81]
The blog is [here](https://medium.com/my-experience-with-opencode-2018/my-experience-of-opencode-2018-7a26415da76), an excerpt from the blog telling about her experience will be good.
A good UI is expected as it will be a new section.

**Comment by CleverFool77** [comment]
@opencodebot claim

**Comment by CleverFool77** [comment]
@opencodebot claim
